application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

spring:
  datasource:

    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0

      # User: Yeni proje ID'ni içeren kullanıcı adın
    username: postgres.jizlqahrhyzvdbjygaaa

      # Belirlediğin şifre
    password: sifredeneme123

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # 'update': Entity sınıflarında değişiklik yaptıkça DB tablosunu otomatik günceller.
      # Geliştirme aşamasında çok faydalıdır.
      ddl-auto: update
    show-sql: true # Hibernate'in arka planda ürettiği SQL sorgularını konsolda görmeni sağlar (öğrenmek için harika!)
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Uygulamanın çalışacağı port
server:
  port: 8080