services:
  db:
    image: postgres:15
    container_name: ebook-db
    environment:
      POSTGRES_DB: ebookdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./ebook-backend
    container_name: ebook-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ebookdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  frontend:
    build: ./ebook-frontend
    container_name: ebook-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
